### ISSUE TITLE
google map api

### ISSUE THREAD

**Issue by szbence89** [revkusz/ultratitkosrepo#1]
üdv, 

a cégünk google maps api kulcsát használjátok a projektben.
ki tudnátok cserélni sajátra?

ps: ultratitkosrepo --> beállítás alapján egy nyilvános repo :)

**Comment by revkusz** [comment]
helló!

Igen az imént megtettem mindenhol ahol nálunk a projectben előfordult!

ps: úgy tűnik az elnevezéses master plan nem jött össze :(
